export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A serene mountain valley at sunrise with misty clouds hovering above and a sparkling river cutting through the lush green forest',
  'An enchanted forest glowing with bioluminescent plants, fairylike fireflies, and a mystical golden pathway',
  'A picturesque tropical beach during sunset with golden sands, turquoise waters, and a lone hammock tied between palm trees',
  'A snow-covered village nestled in the mountains, with cozy wooden cabins emitting warm light and smoke rising from chimneys',
  'A vibrant coral reef underwater, teeming with colorful fish, sea turtles, and coral structures swaying with the current',
  'A futuristic cityscape with flying cars, towering glass buildings, and a vivid neon-lit sky',
  'A dragon perched on a rocky cliff, wings outstretched, roaring as lightning flashes behind it in a stormy sky',
  'An astronaut standing on a distant alien planet, surrounded by glowing alien flora and a massive ringed planet looming in the sky',
  'A magical library with floating books, spiraling staircases, and glowing runes etched on ancient tomes',
  'A robot companion standing in a bustling futuristic marketplace, assisting its human owner with colorful goods all around',
  'A bustling medieval marketplace with merchants selling goods, knights in shining armor, and children playing in the cobbled streets',
  'A traditional Japanese tea house surrounded by cherry blossoms in full bloom during springtime',
  'An ancient Egyptian pyramid under a starry desert sky, with explorers holding torches near the entrance',
  'A Victorian-era street scene with gas lamps, horse-drawn carriages, and people in elegant attire strolling along',
  'A Mayan temple deep in the jungle, with vines hanging from the structure and wildlife lurking nearby',
  'A vibrant city park during autumn, with people jogging, children playing, and colorful leaves scattered on the ground',
  'A modern art museum interior, with futuristic sculptures, interactive exhibits, and people admiring the artwork',
  'A cozy coffee shop on a rainy evening, with warm lighting, customers reading books, and raindrops on the window',
  'A busy street food market at night, with colorful lights, sizzling grills, and a variety of delicious dishes being served',
  'A stylish rooftop bar overlooking a city skyline at sunset, with people enjoying cocktails and live music',
  'A young anime warrior standing atop a mountain cliff, wielding a glowing katana, with a swirling red and black sunset in the background',
  'A futuristic anime city with massive skyscrapers, holographic billboards, and a protagonist with neon-colored hair gazing into the distance',
  'An intense anime-style battle scene with two characters clashing swords, surrounded by shockwaves and fiery explosions',
  'A peaceful anime countryside with cherry blossom trees, a cozy wooden house, and a character sipping tea while sitting on the porch',
  'A magical anime school, with students in unique uniforms casting spells in a glowing arena surrounded by ancient ruins',
  'A superhero with a futuristic metallic suit flying over a bustling city at night, illuminated by glowing blue streaks of light',
  'A powerful superhero team assembled on top of a skyscraper, each with unique costumes and glowing auras representing their abilities',
  'A lone masked vigilante standing under a streetlight in a dark alley, with rain pouring down and the faint glow of a distant city',
  'A superhero and their archnemesis locked in an epic battle in the middle of a collapsing bridge, with sparks and debris flying everywhere',
  'A stealthy ninja-inspired superhero leaping between rooftops in a dystopian city, with a glowing katana and a high-tech visor',
];
